


CREATE DATABASE IF NOT EXISTS test;
USE test;

DROP TABLE IF EXISTS test;

CREATE TABLE test.Test (
  Id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nom VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY(Id)
)
ENGINE = InnoDB;